# Generated by Django 4.0.5 on 2022-06-07 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('laptop_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('brand', models.CharField(max_length=80)),
                ('ram', models.CharField(max_length=20)),
                ('rom', models.CharField(max_length=20)),
                ('HDD', models.CharField(max_length=20)),
                ('SSD', models.CharField(max_length=20)),
                ('price', models.FloatField()),
            ],
        ),
    ]
