# Generated by Django 4.0.5 on 2022-06-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaptopApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='brand',
            field=models.CharField(choices=[('Dell', 'Dell'), ('HP', 'HP'), ('Lenovo', 'Lenovo'), ('Acer', 'Acer')], max_length=80),
        ),
    ]
